/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => Opener
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// node_modules/monkey-around/mjs/index.js
function around(obj, factories) {
  const removers = Object.keys(factories).map((key) => around1(obj, key, factories[key]));
  return removers.length === 1 ? removers[0] : function() {
    removers.forEach((r) => r());
  };
}
function around1(obj, method, createWrapper) {
  const original = obj[method], hadOwn = obj.hasOwnProperty(method);
  let current = createWrapper(original);
  if (original)
    Object.setPrototypeOf(current, original);
  Object.setPrototypeOf(wrapper, current);
  obj[method] = wrapper;
  return remove;
  function wrapper(...args) {
    if (current === original && obj[method] === wrapper)
      remove();
    return current.apply(this, args);
  }
  function remove() {
    if (obj[method] === wrapper) {
      if (hadOwn)
        obj[method] = original;
      else
        delete obj[method];
    }
    if (current === original)
      return;
    current = original;
    Object.setPrototypeOf(wrapper, original || Function);
  }
}

// settings.ts
var import_obsidian = require("obsidian");
var OpenerSettingTab = class extends import_obsidian.PluginSettingTab {
  display() {
    const { containerEl } = this;
    const plugin = this.plugin;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("New Tab Default").setDesc(
      "Enable to open new files in a new tab (or existing tab, if it was previously opened). Disable for default Obsidian behavior."
    ).addToggle(
      (toggle) => toggle.setValue(plugin.settings.newTab).onChange((value) => {
        plugin.settings.newTab = value;
        plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("PDF Default App").setDesc(
      "Enable to open pdfs with system viewer app. Disable for default behavior (open pdfs in Obsidian)."
    ).addToggle(
      (toggle) => toggle.setValue(plugin.settings.PDFApp).onChange((value) => {
        plugin.settings.PDFApp = value;
        plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Open everything outside of Obsidian").setDesc(
      "Enable to open all obsidian supported extensions with system viewer instead. Disable for default behavior (open within Obsidian). Defaults supported extensions are 'png', 'webp', 'jpg', 'jpeg', 'gif', 'bmp', 'svg', 'mp3', 'webm', 'wav', 'm4a', 'ogg','3gp', 'flac', 'mp4', 'ogv', 'mov', 'mkv'."
    ).addToggle(
      (toggle) => toggle.setValue(plugin.settings.allExt).onChange((value) => {
        plugin.settings.allExt = value;
        plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Open Outside Obsidian: Manual List").setDesc("This shouldn't be necessary, but you can manually enable custom extensions here.").addToggle(
      (toggle) => toggle.setValue(plugin.settings.custExt).onChange((value) => {
        plugin.settings.custExt = value;
        plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Open Outside Obsidian: Manual List").setDesc("Enter extension names (without the dot, ie, just docx separated by newlines).").addTextArea((textArea) => {
      textArea.setValue(plugin.settings.custExtList.join("\n")).onChange(async (value) => {
        plugin.settings.custExtList = value.split("\n");
        plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Open Inside Obsidian: Manual List").setDesc("For example, if you're using HTMLViewer plugin that lets you view HTML inside Obsidian.").addToggle(
      (toggle) => toggle.setValue(plugin.settings.custExtIn).onChange((value) => {
        plugin.settings.custExtIn = value;
        plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Open Inside Obsidian: Manual List").setDesc("Enter extension names (without the dot, ie, just docx separated by newlines).").addTextArea((textArea) => {
      textArea.setValue(plugin.settings.custExtInList.join("\n")).onChange(async (value) => {
        plugin.settings.custExtInList = value.split("\n");
        plugin.saveSettings();
      });
    });
  }
};

// constants.ts
var DEFAULT_SETTINGS = {
  newTab: true,
  PDFApp: true,
  allExt: false,
  custExt: false,
  custExtList: [],
  custExtIn: false,
  custExtInList: []
};

// main.ts
var Opener = class extends import_obsidian2.Plugin {
  async onload() {
    console.log("loading " + this.manifest.name + " plugin");
    await this.loadSettings();
    this.addSettingTab(new OpenerSettingTab(this.app, this));
    this.monkeyPatchopenFile();
    this.monkeyPatchopenLinkText();
    this.addCommand({
      id: "open-graph-view-in-new-tab",
      name: "Open Graph View in new tab",
      callback: () => {
        this.app.commands.executeCommandById("workspace:new-tab");
        this.app.commands.executeCommandById("graph:open");
      }
    });
  }
  onunload() {
    this.uninstallMonkeyPatch && this.uninstallMonkeyPatch();
    console.log("unloading " + this.manifest.name + " plugin");
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  monkeyPatchopenFile() {
    const parentThis = this;
    this.uninstallMonkeyPatch = around(import_obsidian2.WorkspaceLeaf.prototype, {
      openFile(oldopenFile) {
        return async function(file, openState) {
          var _a;
          const ALLEXT = ["png", "webp", "jpg", "jpeg", "gif", "bmp", "svg", "mp3", "webm", "wav", "m4a", "ogg", "3gp", "flac", "mp4", "ogv", "mov", "mkv"];
          const OBSID_OPENABLE = ALLEXT.concat(["md", "canvas", "pdf"]);
          if (parentThis.settings.PDFApp && file.extension == "pdf" || parentThis.settings.allExt && ALLEXT.includes(file.extension) || parentThis.settings.custExt && parentThis.settings.custExtList.includes(file.extension) || !OBSID_OPENABLE.includes(file.extension) && (!parentThis.settings.custExtIn || parentThis.settings.custExtIn && !parentThis.settings.custExtInList.includes(file.extension))) {
            app.openWithDefaultApp(file.path);
            return;
          }
          let openElsewhere = false;
          const sameFile = file.path == ((_a = app.workspace.getActiveFile()) == null ? void 0 : _a.path);
          if (sameFile) {
            oldopenFile && oldopenFile.apply(this, [file, openState]);
            return;
          } else if (parentThis.settings.newTab && !sameFile) {
            app.workspace.iterateAllLeaves((leaf) => {
              var _a2;
              if (((_a2 = leaf.getViewState().state) == null ? void 0 : _a2.file) == file.path && leaf.getViewState().type != "canvas") {
                oldopenFile && oldopenFile.apply(leaf, [file, openState]);
                openElsewhere = true;
              }
            });
            if (!openElsewhere && parentThis.settings.newTab && !sameFile) {
              const emptyLeaves = app.workspace.getLeavesOfType("empty");
              if (emptyLeaves.length > 0) {
                oldopenFile && oldopenFile.apply(emptyLeaves[0], [file, openState]);
                return;
              } else if (emptyLeaves.length <= 0) {
                oldopenFile && oldopenFile.apply(this.app.workspace.getLeaf("tab"), [
                  file,
                  openState
                ]);
                return;
              }
            }
          } else if (!parentThis.settings.newTab) {
            oldopenFile && oldopenFile.apply(this, [file, openState]);
            return;
          }
        };
      }
    });
  }
  // if note already exists, monkeyPatchopenFile() does its job and moves to that one. but openLinkText() with options selected for new tab (invoked via Right Click > Open in New Tab or Quick Switcher Cmd+Enter, etc) will still open a new tab.
  monkeyPatchopenLinkText() {
    let parentThis = this;
    this.uninstallMonkeyPatch = around(import_obsidian2.Workspace.prototype, {
      openLinkText(oldOpenLinkText) {
        return async function(linkText, sourcePath, newLeaf, openViewState) {
          if (newLeaf == "tab" || newLeaf == true) {
            newLeaf = false;
          } else {
            app.workspace.iterateAllLeaves((leaf) => {
              var _a;
              if (((_a = leaf.getViewState().state) == null ? void 0 : _a.file) == sourcePath) {
                newLeaf = false;
              }
            });
          }
          oldOpenLinkText && oldOpenLinkText.apply(this, [
            linkText,
            sourcePath,
            newLeaf,
            openViewState
          ]);
        };
      }
    });
  }
};
